apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
  namespace: test-slurm
spec:
  type: ClusterIP
  selector:
    app: config-server
  ports:
  - name: config
    port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-lb
  namespace: test-slurm
spec:
  type: LoadBalancer
  selector:
    app: config-server
  ports:
  - name: config
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: test-slurm
spec:
  replicas: 1  # Number of replicas, adjust as needed
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      setHostnameAsFQDN: true
      serviceAccountName: slurm-config-sa
      containers:
      - name: config-server
        image: bradenacurtis801/slurm:config-server_v1.2.0
        ports:
        - containerPort: 3000
        # command: ["/bin/sh", "-c", "sleep infinity"]

