apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
  namespace: test-slurm
spec:
  clusterIP: None
  selector:
    app: config-server
  ports:
  - name: config
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: config-server
  namespace: test-slurm
spec:
  serviceName: "config-server-svc"
  replicas: 1  # Number of replicas, adjust as needed
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      setHostnameAsFQDN: true
      serviceAccountName: slurm-config-sa
      containers:
      - name: config-server
        image:  bradenacurtis801/slurm-kubernetes-config-server:v1.0.0
        # command: ["/bin/sh", "-c", "sleep infinity"]
  # volumeClaimTemplates:  # This section is optional if persistent storage is needed
  # - metadata:
  #     name: config-server-data
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 1Gi

  # config-server-0.config-server-svc.test-slurm.svc.cluster.local